### ISSUE TITLE
No scape

### ISSUE THREAD

**Issue by miquelgiru** [traguill/Starcraft#1]
When you start an attck on an enemy unit your unit can't escape

**Comment by miquelgiru** [comment]
Class: Major
Type: Gameplay
Frequency: 90%
Step: Once a unit enters in combat it can not move until is has finished
result: no escape

**Comment by traguill** [comment]
Try now :+1: .
If the enemy chases you sometimes you can see one attack frame. This would be another bug, but minor this time :)
