### ISSUE TITLE
No die animation in Firebat [minor]

### ISSUE THREAD

**Issue by auusi9** [traguill/Starcraft#51]
Type: Graphics
Low Priority
Minor Bug
Frequency:100%
Description of the bug: Enemies in the screenshot doesnt have die animation
Steps to reproduce: 
1- Kill this enemies
2- Observe that there is no die animation
![image](https://cloud.githubusercontent.com/assets/10940469/15072486/012c9c8c-138b-11e6-8b05-03d67f54ad4b.png)

**Comment by martipm1** [comment]
Solved, this issue may be closed!
