### ISSUE TITLE
Dead animation bug in sniper mode [major]

### ISSUE THREAD

**Issue by J-Nunes** [traguill/Starcraft#87]
**Class**: Major
**Type**: Graphic
**Frequency**: 100%
**Steps**: 
- Select the ghost.
- Activate sniper ability.
- Kill someone with the sniper.

**Result**:
- During the dead animation, enemy moves to the right.

**Expected result**: 
- During the dead animation, enemy must not move.

**Comment by martipm1** [comment]
It only happens when the unit dying is because of a sniper shot. When in sniping mode, units die as they should.
