### ISSUE TITLE
Sniper uses energy to shoot

### ISSUE THREAD

**Issue by traguill** [traguill/Starcraft#89]
**Class**: B
**Type**: Gameplay 
**Frequency**: 100%
**Steps**: Use the invisibility to get out of energy. Use the sniper and shoot
**Result**: You can't shoot because you don't have energy.
**Expected result**:  Sniper should not use energy to shoot

**Comment by AleixBueso** [comment]
comor? vols que sigui free fer sniper?

**Comment by traguill** [comment]
@AleixBueso  we have limited bullets. Why spend energy to use the sniper? If the player has used all the energy using invisibility he can't shoot.

**Comment by AleixBueso** [comment]
pero no deixa de ser una habilitat
